services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/NewYork
    volumes:
      - /home/docker/jellyfin/config:/config
      - /mnt/LinuxISO/Media:/media
    ports:
      - 8096:8096
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    restart: unless-stopped
networks:
  dockge_default:
    external: true